# -*- coding: utf-8 -*-
"""1 series and dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_37cWa-Bju7LGdo5b1I8I2hjg793ZTR

### Pandas Series

A Series is a one-dimensional labeled array.

Think of it like:

A single column of a table

Or a vector with labels (index)
"""

import pandas as pd

s = pd.Series([10, 20, 30, 40])
s

#series with custom index
marks = pd.Series([85, 90, 88], index=["Ananda", "Sita", "Ram"])
marks

marks[0]

"""# Pandas DataFrame (2-D data)
What is a DataFrame?

A DataFrame is a table (rows + columns), like Excel or SQL table
"""

df = pd.DataFrame({
    "Name": [
        "Sujan Adhikari", "Suman Adhikari", "Sita Gurung", "Sujata Bhattarai",
        "Arun Sharma", "Rajesh Magar", "Sunita Rai", "Prakash Thapa",
        "Sujata Adhikari", "Suman Gurung", "Roshan Poudel", "Urmila Poudel",
        "Shreya Poudel", "Sneha Bhattarai", "Anjali Rai", "Ashish Gurung",
        "Binita Poudel", "Sita Poudel", "Sita Magar", "Anjali Adhikari",
        "Sunita Thapa", "Sunita Bhattarai", "Muna Karki", "Ashish Karki",
        "Sita Shrestha", "Dipesh Adhikari", "Deepak Thapa", "Milan Poudel",
        "Anita Gurung", "Bhawana Bhattarai", "Santosh Poudel", "Binita Rai",
        "Sunita Gurung", "Hari Bhattarai", "Ashish Thapa", "Arun Gurung",
        "Samjhana Rai", "Yogesh Magar", "Ananda Shrestha", "Nabin Karki",
        "Samjhana Gurung", "Kiran Thapa", "Bhawana Adhikari", "Santosh Shrestha",
        "Rekha Rai", "Dinesh Rai", "Prakash Bhattarai", "Sunita Sharma",
        "Rita Sharma", "Rekha Gurung", "Urmila Sharma", "Santosh Sharma",
        "Laxmi Rai", "Anjali Bhattarai", "Gopal Shrestha", "Pratima Shrestha",
        "Rekha Poudel", "Ashish Bhattarai", "Puja Magar", "Samjhana Shrestha",
        "Ram Gurung", "Sujata Shrestha", "Sabina Magar", "Sneha Rai",
        "Nisha Shrestha", "Laxmi Shrestha", "Anjali Sharma", "Dipesh Gurung",
        "Sarita Sharma", "Amrit Rai", "Sujan Thapa", "Prerana Poudel",
        "Gopal Magar", "Kabita Magar", "Manisha Karki", "Milan Sharma",
        "Bishal Magar", "Ram Shrestha", "Anita Karki", "Sunita Poudel",
        "Rita Magar", "Arun Karki", "Yogesh Rai", "Alina Karki",
        "Suman Thapa", "Yogesh Adhikari", "Shreya Rai", "Sabina Gurung",
        "Sujan Magar", "Gopal Poudel", "Kiran Shrestha", "Gopal Bhattarai",
        "Gopal Thapa", "Deepak Adhikari", "Roshan Shrestha", "Puja Poudel",
        "Alina Sharma", "Roshan Bhattarai", "Anita Thapa", "Bishal Poudel",
    ],
    "Age": [
        27, 28, 20, 26, 29, 21, 20, 25, 24, 22, 28, 29, 26, 21, 28, 23, 30, 30, 18, 21,
        18, 30, 23, 24, 22, 19, 21, 27, 29, 23, 21, 28, 25, 24, 28, 25, 20, 22, 20, 21,
        29, 26, 26, 22, 29, 27, 24, 27, 24, 23, 21, 20, 26, 25, 19, 30, 18, 19, 20, 28,
        20, 30, 28, 24, 27, 19, 24, 24, 27, 25, 26, 22, 26, 18, 28, 29, 19, 28, 26, 30,
        22, 30, 28, 23, 19, 22, 24, 20, 25, 18, 29, 29, 22, 26, 30, 20, 26, 19, 28, 22,
    ],
    "Score": [
        90, 82, 88, 62, 59, 73, 98, 60, 84, 99, 83, 50, 88, 70, 81, 51, 57, 73, 69, 65,
        53, 65, 86, 55, 55, 96, 81, 54, 98, 84, 99, 58, 58, 92, 80, 85, 60, 66, 83, 88,
        77, 63, 84, 98, 96, 94, 62, 95, 69, 75, 92, 91, 73, 78, 83, 78, 57, 65, 64, 54,
        71, 51, 87, 85, 64, 87, 64, 50, 54, 95, 90, 53, 64, 54, 52, 71, 54, 82, 65, 67,
        92, 81, 63, 84, 58, 96, 86, 86, 80, 65, 100, 80, 76, 62, 56, 56, 92, 77, 72, 77,
    ],
})
df

"""### Select Columns (very important)
#### Single column → Series
### Multiple columns → DataFrame
"""

df["Age"]

df[["Name", "Score","Age"]]

### Now use all the general method for this dataframe like and find first 2 data last two data info and shape
df.head()

df.tail(5)

df.shape

df.head(1)

df.sample()

df = pd.DataFrame({
    "Name": [
        "Ananda", "Sita", "Ram", "Gita", "Hari", "Nita", "Ravi", "Pooja", "Kiran", "Maya",
        "Amit", "Sneha", "Rohan", "Anita", "Bikash", "Nisha", "Rahul", "Puja", "Suman", "Kavita",
        "Arjun", "Neha", "Sagar", "Rita", "Manish", "Sunita", "Deepak", "Priya", "Rohit", "Alina",
        "Vikas", "Mina", "Nabin", "Komal", "Dipesh", "Laxmi", "Prakash", "Isha", "Niraj", "Asha",
        "Suraj", "Riya", "Santosh", "Anjali", "Hemant", "Pawan", "Monika", "Ashok", "Preeti", "Sonia"
    ],
    "Age": [
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21
    ],
    "Score": [
        85, 90, 88, 76, 92, 81, 87, 79, 84, 90,
        86, 78, 91, 83, 89, 80, 88, 82, 90, 77,
        85, 84, 92, 79, 88, 81, 90, 83, 87, 86,
        91, 78, 84, 82, 89, 80, 88, 85, 92, 77,
        90, 83, 91, 79, 86, 84, 88, 81, 90, 85
    ]
})

df



# save the generated data into local system
df.to_csv('data.csv', index=False)  # index=False avoids adding row numbers

# apply all the analysis like info shape ,describe and others things in your data and find the first 10 and last 10 data
df.head(10)

df.sample()

df.info()

df.describe()

# your task generate the another data using the list

df = pd.DataFrame ({
    "company" : [
    "Everest Traders","Himalayan Foods","Annapurna Steel","Gorkha Textiles","Lumbini Cement",
    "Kathmandu Motors","Pokhara Plastics","Sagarmatha Tea","Bagmati Chemicals","Janaki Garments",
    "Machhapuchhre Mills","Rara Beverages","Chitwan Agro","Terai Sugar","Kailash Paper",
    "Dhaulagiri Iron","Manaslu Cables","Langtang Dairy","Mustang Apparel","Bardiya Timber",
    "Nepal Ceramics","Siddhartha Pharma","Trishuli Power","Karnali Mines","Koshi Fisheries",
    "Ganesh Electronics","Buddha Air Parts","Solu Cement","Rasuwa Herbals","Palpa Furniture",
    "Illam Tea Estate","Birat Polymers","Nuwakot Foods","Dolpa Wool","Jumla Apples",
    "Sindhu Steelworks","Makalu Glass","Kanchan Paints","Bhotekoshi Hydro","Tilicho Textiles",
    "Rapti Rubber","Narayani Oils","Seti Packaging","Sunkoshi Cement","Marsyangdi Power",
    "Arun Valley Agro","Barun Bricks","Gandaki Plywood","Kali Gandaki Steel","Phewa Foods",
    "Begnas Bottling",	"Shivapuri Spices","Nagarkot Coffee","Dhading Poultry","Kavre Dairy",
    "Ramechhap Iron","Okhaldhunga Mills","Bhojpur Handicrafts","Taplejung Cardamom","Dhankuta Foods",
    "Sarlahi Sugar","Mahottari Rice","Rautahat Jute","Parsa Plastics","Bara Cement",
    "Nawalpur Agro","Kapilvastu Grains","Dang Foods","Banke Textiles","Surkhet Herbals",
    "Jajarkot Minerals","Salyan Timber","Rukum Stone","Baglung Metals","Myagdi Hydro",
    "Parbat Foods","Syangja Dairy","Tanahun Cement","Gulmi Coffee","Arghakhanchi Mills",
    "Rolpa Agro","Pyuthan Poultry","Bajura Wool","Achham Herbals","Doti Timber",
    "Kailali Rice","Kanchanpur Sugar","Dadeldhura Foods","Baitadi Crafts","Darchula Stone",
    "Solukhumbu Treks","Khumbu Outfitters","Thamel Exports","Patan Metalcraft","Bhaktapur Pottery",
    "Lalitpur Logistics","Newroad Retail","Balaju Industries","Hetauda Refinery","Butwal Motors",
],
    "sales" : [
    4520, 8790, 15230, 6340, 12480, 21750, 3980, 5620, 9340, 7120,
    11250, 4870, 6930, 18400, 5240, 14680, 8250, 9870, 4310, 3760,
    7480, 16920, 24350, 19870, 5130, 13460, 22140, 11890, 3420, 4980,
    8640, 6270, 5810, 2940, 3580, 17230, 9120, 10480, 26340, 7690,
    6150, 12730, 5470, 15890, 23180, 4260, 3310, 8930, 18650, 6820,
    3940, 4710, 5290, 7360, 8140, 13920, 6580, 2870, 4430, 5960,
    16240, 11470, 6890, 9530, 20180, 7240, 8670, 5380, 6740, 4190,
    10360, 5720, 3860, 12140, 21630, 4580, 7910, 14270, 3690, 6410,
    5170, 4820, 2760, 3520, 4060, 11830, 15340, 5640, 3180, 2650,
    9280, 7530, 13680, 6120, 4740, 8460, 10920, 12570, 28450, 19240,
],

    "profit": [
    610, 1320, 2140, 780, 1690, 3480, 420, 730, 1180, 940,
    1570, 560, 810, 2760, 620, 2050, 1140, 1290, 480, 390,
    970, 2380, 4120, 2640, 610, 1830, 3520, 1470, 310, 570,
    1160, 720, 640, 240, 380, 2410, 1230, 1360, 4680, 890,
    740, 1780, 590, 2230, 3760, 460, 290, 1210, 2540, 810,
    420, 530, 610, 880, 1090, 1950, 760, 240, 470, 690,
    2280, 1520, 830, 1240, 2870, 890, 1130, 620, 780, 430,
    1420, 640, 390, 1680, 3240, 510, 1020, 1960, 340, 750,
    580, 490, 210, 360, 430, 1610, 2190, 640, 290, 180,
    1240, 940, 1870, 720, 510, 1080, 1450, 1730, 5120, 2760,
]
})
df

df.head(10)

df.tail(10)

df.info()

df.describe()

df["company"]

df[["company","sales"]]

df.shape



"""### you can add your own note below using pandas offical documentation https://pandas.pydata.org/docs/

### your task find and write the detailed comparison between series and dataframe with code example
"""

# Series -  1D labeled Data
#Dataframe - 2D labeled Data

s = pd.Series([85, 90, 88], index=["Ananda", "Sita", "Ram"], name="Score")
print(s)



df = pd.DataFrame({
    "Name":  ["Ananda", "Sita", "Ram"],
    "Age":   [22, 21, 23],
    "Score": [85, 90, 88],
})
print(df)

