# -*- coding: utf-8 -*-
"""conndition (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgKbMd4NGd-Iln27G14_7V_JrNimn9lx
"""

import pandas as pd


df = pd.read_csv("/content/titanic.csv")
df.head(10)

# syntax for loc
#df.loc[row_condition, column_selection]

df[df["Age"]>30]

df.loc[df["Age"]>30,["Age","Name","Fare"]]

"""Name and fare of passenger whose age is greater than 40."""

df.loc[df["Age"]>40,["Name","Fare","Age"]]

# Passengers who survived
df.loc[df["Survived"] == 1, ["Name","Age","Survived"]]

df

#Passengers in 1st class
df.loc[df["Pclass"]==1,["Name","Age","Pclass","Sex"]]

# Age > 30 AND Survived
df.loc[(df["Age"] > 30) & (df["Survived"] == 0), :]

# Age < 18 OR Female
new_dfc= df.loc[(df["Age"]<18) | (df["Sex"] == "female"), :]

new_dfc

# make a 5 question  live and practice

# find out the members numbers  of 3rd class who is female and show only pclass sex and name column
df.loc[(df["Pclass"]==3) & (df["Sex"]=="female"),["Pclass","Sex","Name"]]

# find out the members numbers  of 3rd class who is male
df.loc[(df["Pclass"]==3)  &  (df["Sex"]=="male")]

# Female passengers older than 25
df.loc[(df["Sex"] == "female") & (df["Age"] > 25), ["Name", "Age", "Pclass"]]

# Average age of survivors
df.loc[df["Survived"]==1,"Age"].mean()

#Rich passengers (Fare > 100) who survived only find name and age

# find the name and age of Children (<15) in 3rd class

# Count passengers older than 60
df.loc[df["Age"] > 60, :].shape[0]

# your task take a another datasets and make a 30 to 50 question and do a practcie like this

