# -*- coding: utf-8 -*-
"""groupby.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15cxUsp0FlIvjnAY3vophdH4W4IVe1yvE
"""

import pandas as pd
import numpy as np

data = {
'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance', 'IT'],
'Employee': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
'Salary': [50000, 40000, 55000, 60000, 42000, 65000, 58000],
'Experience': [2, 1, 3, 5, 2, 6, 4]
}


df = pd.DataFrame(data)
df

df.head()

df.sample(5)

df.info()

df.describe()

"""3. What is GroupBy?

groupby() is used to split data into groups, apply a function, and combine results.

Split → Apply → Combine

Basic GroupBy (Single Column)
Group by Department
"""

df.groupby('Department')

df.groupby('Department')['Salary'].mean()
#Calculate Mean Salary per Department

df.groupby ("Department")['Salary'].min()

# Multiple Aggregations
df.groupby('Department')['Salary'].agg(['mean', 'max', 'min', 'sum'])

# GroupBy with Multiple Columns
df.groupby(['Department', 'Experience'])['Salary'].mean()

df.groupby('Department')['Employee'].count()
#Using GroupBy with Count

def salary_range(x):         #when no built function is in pandas we use default function to give our logic
 return x.max() - x.min()


df.groupby('Department')['Salary'].apply(salary_range)

# titanic datasets

import pandas as pd

df = pd.read_csv("/content/titanic.csv")
df.head()

#Average Fare per Passenger Class
df.groupby('Pclass')['Fare'].mean()

df.groupby('Sex')['Survived'].mean()
#Survival Rate by Gender

# Multiple Aggregations
df.groupby('Pclass')['Fare'].agg(['mean', 'max', 'min', 'count'])

df

df.groupby('Embarked')['Fare'].mean()

#GroupBy Multiple Columns
df.groupby(['Pclass', 'Sex'])['Survived'].mean()

# Average age of survivors vs non-survivors
df.groupby('Survived')['Age'].mean()

# Count of male and female passengers per class
df.groupby(['Pclass', 'Sex']).size()

df["average age "]=df.groupby("Sex")["Age"].mean()

df

# Which embark town has highest survival rate?

df.groupby("Embarked")["Age"].mean()

import pandas as pd

df = pd.read_csv("/content/sales_group.csv")
df.head()

#total number of orders for each city
df.groupby("city")['quantity'].count()

#total number of order for each product category
df.groupby("category")['order_id'].count()

#total quantity of products sold for each category
df.groupby("category")['quantity'].sum()

#average unit_price for each product category
df.groupby ("category")['unit_price'].mean()

#maximum unit_price for each category
df.groupby ("category")['unit_price'].max()

#minimum unit_price for each category
df.groupby ("category")['unit_price'].min()

#total quantity sold for each product
df.groupby ("product")['quantity'].sum()

#total number of orders handlesd by each salesperson 
df.groupby ("salesperson")['order_id'].count()

#total sales amount for each category 
df.groupby ("category")['unit_price'].sum()

# total sales amount for each category.
df["sales_amount"] = df["quantity"] * df["unit_price"]
df.groupby("category")["sales_amount"].sum()


