# -*- coding: utf-8 -*-
"""pandas_selection_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-GQjUrjZDdhzLHtaD5FzTXeWUnOMT8Z

# Pandas Data Selection — `[ ]`, `.loc`, `.iloc`
**Prepared by Ananda Rimal** · Dataset: Titanic

In this notebook we learn the 3 ways to select data from a DataFrame:

| Method | Selects by | Example |
|--------|-----------|---------|
| `df["col"]` | column name | `df["Age"]` |
| `df.loc[...]` | **labels** (names) | `df.loc[0:4, ["Name","Age"]]` |
| `df.iloc[...]` | **positions** (numbers) | `df.iloc[0:5, 0:3]` |
"""

import pandas as pd

df = pd.read_csv("/content/titanic.csv")   # change the path if needed
df.head()

df.info()

df.describe()

"""## 1. Selecting Columns"""

# Single column -> returns a SERIES (1 column)
df["Age"]

# List of columns -> returns a DATAFRAME (note the double brackets!)
df[["Name", "Sex", "Age"]]

"""## 2. `.loc` — Label-based Selection (VERY IMPORTANT)

Syntax: `df.loc[row_label, column_label]`

`.loc` uses the **index labels** and column **names**.
"""

# Rows with labels 0 to 4  (loc INCLUDES the end -> 5 rows!)
df.loc[0:4]

# Rows + specific columns together
df.loc[0:4, ["Name", "Age", "Sex"]]

# One row, selected columns
df.loc[0, ["Name", "Age"]]

# ALL rows, specific columns  (the ':' means 'everything')
df.loc[:, ["Survived", "Pclass", "Fare"]].mean()

"""## 3. `.iloc` — Position-based Selection

Syntax: `df.iloc[row_position, column_position]`

`.iloc` uses **integer positions** (0, 1, 2, ...) — like a list.
"""

df.head()

# First 5 rows  (iloc EXCLUDES the end -> positions 0,1,2,3,4)
df.iloc[0:5]

# Rows AND columns by position: first 5 rows, first 3 columns
df.iloc[0:5, 0:3]

"""## 4. The Key Difference: `loc` vs `iloc`

| | `.loc[0:4]` | `.iloc[0:4]` |
|---|---|---|
| Selects by | label | position |
| End included? | **YES** (5 rows) | **NO** (4 rows) |

**Tip: GENERALLY USE `.loc` INSTEAD OF `.iloc`** — labels do not change when the data is
sorted or filtered, positions do.

## 5. `set_index` — Now Labels and Positions Are DIFFERENT

Until now the index labels (0,1,2,...) happened to equal the positions, so `loc` and `iloc`
looked the same. Watch what happens when we make **PassengerId** the index.
"""

df.set_index("PassengerId", inplace=True)
df.head()

# Now the index labels are 1...891 (PassengerId), but positions are still 0...890

df.loc[1]       # LABEL 1  -> passenger with PassengerId = 1  (the FIRST row)

df.iloc[887]    # POSITION 887 -> the 888th row (its PassengerId label is 888)

# Same passenger, two ways:
print("By label   ->  df.loc[888]")
print("By position ->  df.iloc[887]")
df.loc[888].equals(df.iloc[887])

"""## Summary

- `df["col"]` -> one column (Series); `df[["c1","c2"]]` -> many columns (DataFrame)
- `.loc[rows, cols]` -> by **labels**, end **included**
- `.iloc[rows, cols]` -> by **positions**, end **excluded**
- After `set_index`, labels and positions become different — `.loc` follows the new index
- Prefer `.loc` in daily work

## 10 Practice Questions

*(Use the Titanic DataFrame. Q1–Q8: before `set_index`; Q9–Q10: after `set_index("PassengerId")`.)*

1. Select the `Fare` column as a Series.
2. Select the columns `Name`, `Age`, and `Survived` together in one DataFrame.
3. Select the **first 10 rows** using `.iloc`.
4. Select rows with labels **5 to 10** using `.loc`. How many rows do you get, and why?
5. Using `.loc`, select rows 0 to 4 with only the columns `Name` and `Pclass`.
6. Using `.iloc`, select the first 5 rows and the first 4 columns.
7. Using `.loc`, get the value of column `Sex` for the row with label 3.
8. Select the **last row** of the DataFrame using `.iloc` (hint: negative position).
9. After `set_index("PassengerId")`, select the passenger with **ID 100** using `.loc`.
10. Select that SAME passenger using `.iloc`. Which position number did you need, and why is it different from 100?
"""

df["Fare"]

new_data=df[["Age","Name","Survived"]]

new_data

df.loc[5:10]

df.loc[3,"Sex"]

df.loc[3, ["Sex","Name"]]

df.iloc[-1]

df.loc[100]

df.iloc[99]