# -*- coding: utf-8 -*-
"""sorting (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aui_4IAypps3dR6Lulm8o1lzbIaaazQr
"""

import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Age": [22, 19, 25, 21],
    "Marks": [78, 85, 67, 90]
}

df = pd.DataFrame(data)

df

#Sort by Age
df.sort_values(by="Age")

df

# Sort by Marks (ascending)
df.sort_values(by="Marks")

# First by Age, then by Marks
df.sort_values(by=["Age", "Marks"])

import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Age": [22, 19, 22, 21],
    "Marks": [78, 85, 67, 90]
}

df = pd.DataFrame(data)

df.sort_values(by=["Age", "Marks"], ascending=[True, False])
# Different order for each column:

df.sort_index()
# sort by index

df.sort_index(ascending=False)

df

# Sort and save changes (inplace)
df.sort_values(by="Marks", inplace=True)
df

df

# Sort strings (alphabetical order)
df.sort_values(by="Name")

# Reverse alphabetical:
df.sort_values(by="Name", ascending=False)

"""## 🧠 Quick Summary

| Task | Method |
|------|--------|
| Sort rows | `sort_values()` |
| Sort index | `sort_index()` |
| Descending order | `ascending=False` |
| Multiple columns | `by=[...]` |
| Save changes | `inplace=True` |
| Fix index | `reset_index(drop=True)` |

"""

