# -*- coding: utf-8 -*-
"""updating_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBsAQzJZsqJgf42aZRAPBDXSinD5sZPx
"""

import pandas as pd

df = pd.read_csv("/content/titanic.csv")
df.head()

df.info()

#Check original Fare values (before update)
df.loc[df["Survived"] == 1, ["Survived", "Fare"]].head(20)

# Increase Fare by 10 for survivors
df.loc[df["Survived"] == 1, "Fare"] += 10

df

#increse fare by ten for non survivers
df.loc[df["Survived"] == 0, "Fare"] += 10

# Verify update
df.loc[df["Survived"] == 1, ["Survived", "Fare"]].head()

df

df["Age"].isna()

df

# Fill missing Age with 30
df.loc[df["Age"].isna()]

df.loc[df["Age"].isna(), "Age"] = 30

# Fill missing Age with 30
df.loc[df["Age"].isna()]

df

df["Embarked"].sample(5
                      )

# your task :Replace Embarked 'S' with 'Southampton'
df.loc[df["Embarked"] == "S", "Embarked"] = "Southampton"

df

# Increase Age by 1 for male survivors
df.loc[(df["Sex"] == "male") & (df["Survived"] == 1), "Age"] += 1

## your taskSet Fare = 0 for non-survivors in 3rd class
df.loc[(df["Pclass"] == 3) & (df["Survived"] == 0), "Fare"] =0

# Update Age and Fare for 1st class passengers
df.loc[df["Pclass"] == 1, ["Age", "Fare"]] = [40, 100]

# Update Age and Fare for 3rd class passengers
df.loc[df["Pclass"] == 3, ["Age", "Fare"]] = [40, 100]

# Verify multiple column update
df.loc[df["Pclass"] == 1, ["Age", "Fare"]].head()

# Add 20 Fare to Class 1 and 2 passengers
df.loc[df["Pclass"].isin([1, 2]), "Fare"] += 20

# Add 50 Fare to Class 1 and 2 passengers
df.loc[df["Pclass"].isin([1, 2]), "Fare"] += 50

# Verify update
df.loc[df["Pclass"].isin([1, 2]), ["Pclass", "Fare"]].head()

# Fill missing Cabin with "Unknown"
df.loc[df["Cabin"].isna(), "Cabin"] = "Unknown"

df

